[project]
name = "ssp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bestconfig>=1.3.6",
    "pymongo>=4.13.0",
    "streamlit>=1.45.1",
]
